document.addEventListener('DOMContentLoaded', () => {
    // List of integrals (Extracted from your LaTeX file)
    const integrals = [
        "\\int \\tan^5 x \\sec^3 x \\, dx",
        "\\int (2x+5) (x^2+5x)^7 \\, dx",
        "\\int (3x-10)^{10} \\, dx",
        "\\int \\sqrt{7x+10} \\, dx",
        "\\int e^{5x+10} \\, dx",
        "\\int 4\\cos{3x} \\, dx",
        "\\int \\frac{\\sin{\\ln{x}}}{x} \\, dx",
        "\\int \\frac{3x+6}{x^2+4} \\, dx",
        "\\int x (x^2+1) \\, dx",
        "\\int xe^x \\, dx",
        "\\int x \\ln{x} \\, dx",
        "\\int x\\cos{3x} \\, dx",
        "\\int \\frac{\\ln{x}}{x^2} \\, dx",
        "\\int \\arcsin{x} \\, dx",
        "\\int x^2 e^{3x} \\, dx",
        "\\int x^3 \\ln{5x} \\, dx",
        "\\int (\\ln{x})^2 \\, dx",
        "\\int x (x+1) \\, dx",
        "\\int e^{6x} \\, dx",
        "\\int e^x \\cos{x} \\, dx",
        "\\int \\frac{3x}{x^2+1} \\, dx",
        "\\int x\\cos{ax} \\, dx",
        "\\int \\frac{x-1}{x+2} \\, dx",
        "\\int x^4 \\sqrt{x^2+1} \\, dx",
        "\\int \\frac{1}{x^3+2x} \\, dx",
        "\\int z^2(3-2z)^9 \\, dz",
        "\\int 2x^3 \\ln{(x^2+1)} \\, dx",
        "\\int \\ln{(1+x)} \\, dx",
        "\\int \\frac{\\cos{2x}}{1+\\sin^2{x}} \\, dx",
        "\\int \\sqrt{x+4} \\, dx",
        "\\int \\sqrt{x^2-9} \\, dx",
        "\\int e^{\\sqrt{x}} \\, dx",
        "\\int e^{\\cos{x}} \\, dx",
        "\\int \\frac{\\ln{x}}{x^2+1} \\, dx",
        "\\int x\\sqrt{x-1} \\, dx",
        "\\int \\sqrt{t} \\, dt",
        "\\int xe^{-x} \\, dx",
        "\\int \\frac{x^2}{x^3+1} \\, dx",
        "\\int \\frac{\\cos{2x}}{\\sin{x}} \\, dx",
        "\\int x^2 e^{5x} \\, dx",
        "\\int \\ln{(x+3)} \\, dx",
        "\\int \\frac{8x}{x^2+4} \\, dx",
        "\\int -12x^2(4x^3-1)^3 \\, dx",
        "\\int 6x(x^2-1)^2 \\, dx",
        "\\int \\frac{16x}{x^3+1} \\, dx",
        "\\int 18x^2(3x^3+3)^2 \\, dx",
        "\\int \\frac{-8x}{x^2+4} \\, dx",
        "\\int -15x^4(-3x^5-1)^5 \\, dx",
        "\\int \\frac{-16x^3}{x^4+1} \\, dx",
        "\\int \\frac{x}{\\sqrt{x+2}} \\, dx",
        "\\int_{0}^{1} xe^{x^2} \\, dx",
        "\\int_{0}^{\\frac{1}{2}} \\frac{\\arcsin x}{\\sqrt{1-x^2}} \\, dx",
        "\\int_{e}^{e^4} \\frac{dx}{x\\sqrt{\\ln x}} \\, dx",
        "\\int_{0}^{1} \\frac{e^z+1}{e^z+z} \\, dz",
        "\\int_{0}^{1} x\\sin(x^2) \\, dx",
        "\\int (3x-2)^2 \\, dx",
        "\\int \\sin(\\pi t) \\, dt",
        "\\int (x+1)\\sqrt{2x+x^2} \\, dx",
        "\\int \\frac{a+bx^2}{\\sqrt{3ax+bx^3}} \\, dx",
        "\\int \\frac{\\cos\\sqrt{t}}{\\sqrt{t}} \\, dt",
        "\\int \\cos x \\, \\sin^6 x \\, dx",
        "\\int \\csc^2(x)\\sqrt{\\cot x} \\, dx",
        "\\int \\frac{\\cos{\\pi x}}{x^2} \\, dx",
        "\\int x^3\\sqrt{x^2+1} \\, dx",
        "\\int \\sec^3 x\\tan x \\, dx"
    ];

    // Select a random integral
    const randomIntegral = integrals[Math.floor(Math.random() * integrals.length)];

    // Render the selected integral using KaTeX
    katex.render(String.raw`${randomIntegral}`,
        document.getElementById("question"), {
        throwOnError: false
    });
});
